### PR TITLE
Bug fixes and improvements

### PR DESCRIPTION
**Pull request by cyrusnaficy**
1. Removed output like [^1^] [^2^] [^3^] in the response so that the text is a plain response. 

2. Replaced built in fetch with node-fetch. Better for node (more compatible with older versions) plus removes the error below. 

```node:35579) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time (Use `node --trace-warnings ...` to show where the warning was created)```

Already built and tested current PR code.

### CODE REVIEW

**Comment by Niek** [comment]
IMHO replacing with `node-fetch` is not the way to go. Node 18 is LTS and it has native `fetch()` support. Node 19 onwards don't have the warning anymore. In Node 18, you can also suppress it by setting `NODE_NO_WARNINGS=1`.

**Comment by cyrusnaficy** [comment]
> IMHO replacing with `node-fetch` is not the way to go. Node 18 is LTS and it has native `fetch()` support. Node 19 onwards don't have the warning anymore. In Node 18, you can also suppress it by setting `NODE_NO_WARNINGS=1`.

I see what you mean, but wouldn't using `node-fetch`  allow the package to be compatible with older versions? That was the  main reason I added it.

**Comment by transitive-bullshit** [comment]
@cyrusnaficy this article provides a good breakdown of why NPM packages shouldn't polyfill / embed `fetch`: https://www.builder.io/blog/stop-polyfilling-fetch-in-your-npm-package

**Comment by transitive-bullshit** [comment]
@cyrusnaficy thanks a lot for the PR and sorry for not responding til now. I really like the first change, but in the future if you're making multiple changes as a first-time PR to a repo, I'd recommend using multiple, focused PRs. Since in this case, the `node-fetch` changes are coupled with the other ones and I can't merge as-is.

**Comment by cyrusnaficy** [comment]
> @cyrusnaficy thanks a lot for the PR and sorry for not responding til now. I really like the first change, but in the future if you're making multiple changes as a first-time PR to a repo, I'd recommend using multiple, focused PRs. Since in this case, the `node-fetch` changes are coupled with the other ones and I can't merge as-is.

Sounds good. Thanks for the feedback, I really appreciate it. As of now i'll close the PR.

**Pull request closed without merging**
